# Generated by Django 4.2.4 on 2025-01-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ourcompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implemented', models.IntegerField()),
                ('staff', models.IntegerField()),
                ('market', models.IntegerField()),
                ('qualified', models.IntegerField()),
            ],
        ),
    ]
