# Generated by Django 4.2.4 on 2025-01-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_ourcompany_market_remove_ourcompany_qualified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourcompany',
            name='implemented',
        ),
        migrations.AddField(
            model_name='ourcompany',
            name='heading',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ourcompany',
            name='market',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ourcompany',
            name='paragraph',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ourcompany',
            name='project',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ourcompany',
            name='quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ourcompany',
            name='staff',
            field=models.IntegerField(default=0),
        ),
    ]
