# Generated by Django 4.2.4 on 2025-01-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_ourcompany_implemented_ourcompany_heading_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ourcompany',
        ),
    ]
