# Generated by Django 4.2.4 on 2025-01-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_no',
            field=models.CharField(default=0, max_length=70),
        ),
    ]
