# Generated by Django 4.2.4 on 2025-01-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_contact_name_contact_address_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_heading',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='sub_heading',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
