# Generated by Django 4.2.4 on 2025-01-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contact_contact_heading_contact_sub_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='term_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_use', models.CharField(max_length=1000)),
                ('privacy_policy', models.CharField(max_length=1000)),
                ('age_restriction', models.CharField(max_length=1000)),
                ('intellectual_propertye', models.CharField(max_length=1000)),
                ('user_accounts', models.CharField(max_length=1000)),
                ('disputes', models.CharField(max_length=1000)),
                ('indemnification', models.CharField(max_length=1000)),
                ('limitation_on_liability', models.CharField(max_length=1000)),
            ],
        ),
    ]
