# Generated by Django 4.2.4 on 2025-01-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
