# Generated by Django 4.2.4 on 2025-01-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_contactform_address_alter_contactform_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
