# Generated by Django 4.2.4 on 2025-01-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_contactform_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='category',
        ),
    ]
