# Generated by Django 4.2.4 on 2025-01-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_contactform_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='queries',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
