# Generated by Django 4.2.4 on 2025-01-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_contactform_queries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
