# Generated by Django 4.2.4 on 2025-01-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='designer_designation',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='designer_name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='engineer_designation',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='engineer_name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='founder_designation',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='founder_name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_designation',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
