# Generated by Django 4.2.4 on 2025-01-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_team_designation_remove_team_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teximonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teximonial_heading', models.CharField(default=0, max_length=200)),
                ('sub_heading', models.CharField(default=0, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
