# Generated by Django 4.2.4 on 2025-01-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_teximonial_content_teximonial_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teximonial_content',
            name='client_photo',
            field=models.ImageField(blank=True, upload_to='web_photos'),
        ),
    ]
