# Generated by Django 4.2.5 on 2025-01-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_teximonial_content_client_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_company_name', models.CharField(max_length=200)),
                ('landing_heading', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Landing_dynamic_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_photo', models.ImageField(upload_to='web_photos')),
                ('landing_photo_data', models.CharField(max_length=400)),
            ],
        ),
    ]
