# Generated by Django 4.2.5 on 2025-01-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_totalwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('id_card', models.CharField(max_length=400)),
                ('employee_photo', models.ImageField(upload_to='web_photos')),
            ],
        ),
    ]
