# Generated by Django 4.2.5 on 2025-01-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teximonial_dynamic_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_photo', models.ImageField(blank=True, upload_to='web_photos')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Teximonial_heading',
        ),
        migrations.RemoveField(
            model_name='teximonial_content',
            name='client_photo',
        ),
        migrations.RemoveField(
            model_name='teximonial_content',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teximonial_content',
            name='name',
        ),
        migrations.AddField(
            model_name='teximonial_content',
            name='sub_heading',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='teximonial_content',
            name='teximonial_heading',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
