# Generated by Django 4.2.5 on 2025-01-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_teximonial_dynamic_content_delete_teximonial_heading_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_content',
        ),
    ]
