# Generated by Django 4.2.5 on 2025-01-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_rename_contact_contact_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactform',
            new_name='Query_data',
        ),
    ]
