# Generated by Django 4.2.5 on 2025-01-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_rename_contactform_query_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Totalwork',
            new_name='Soceity_work',
        ),
    ]
