# Generated by Django 4.2.5 on 2025-01-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_project_content_project_dynamic_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_heading', models.CharField(default=0, max_length=200)),
                ('sub_heading', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team_dynamic_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(default=0, max_length=200)),
                ('designer_designation', models.CharField(default=0, max_length=100)),
                ('designer_photo', models.ImageField(blank=True, upload_to='web_photos')),
                ('founder_name', models.CharField(default=0, max_length=200)),
                ('founder_designation', models.CharField(default=0, max_length=100)),
                ('founder_photo', models.ImageField(blank=True, upload_to='web_photos')),
                ('manager_name', models.CharField(default=0, max_length=200)),
                ('manager_designation', models.CharField(default=0, max_length=100)),
                ('manager_photo', models.ImageField(blank=True, upload_to='web_photos')),
                ('engineer_name', models.CharField(default=0, max_length=200)),
                ('engineer_designation', models.CharField(default=0, max_length=100)),
                ('engineer_photo', models.ImageField(blank=True, upload_to='web_photos')),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
