# Generated by Django 4.2.5 on 2025-01-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
