# Generated by Django 4.2.5 on 2025-01-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_profile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landing_content',
            name='landing_company_name',
        ),
    ]
