# Generated by Django 4.2.5 on 2025-01-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_remove_landing_content_landing_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_designation',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
