# Generated by Django 4.2.5 on 2025-01-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='About_dynamic_content',
        ),
    ]
