# Generated by Django 4.2.5 on 2025-01-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_rename_about_about_dynamic_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_dynamic_content',
            old_name='Dreams',
            new_name='dreams',
        ),
        migrations.RenameField(
            model_name='about_dynamic_content',
            old_name='Dreams_img',
            new_name='dreams_img',
        ),
        migrations.RenameField(
            model_name='about_dynamic_content',
            old_name='Inspire',
            new_name='inspire',
        ),
        migrations.RenameField(
            model_name='about_dynamic_content',
            old_name='Inspire_img',
            new_name='inspire_img',
        ),
        migrations.AddField(
            model_name='about_dynamic_content',
            name='dreams_head',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about_dynamic_content',
            name='inspire_head',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about_dynamic_content',
            name='vision_head',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
