# Generated by Django 4.2.5 on 2025-01-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_rename_dreams_about_dynamic_content_dreams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(blank=True, max_length=200)),
                ('about_para', models.CharField(max_length=300)),
            ],
        ),
    ]
