# Generated by Django 4.2.5 on 2025-01-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_about_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivement_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivement_heading', models.CharField(blank=True, max_length=200)),
                ('achivement_para', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Achivement_dynamic_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivement_img_one', models.ImageField(upload_to='web_photos')),
                ('achivement_img_two', models.ImageField(upload_to='web_photos')),
            ],
        ),
    ]
