# Generated by Django 4.2.5 on 2025-01-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_achivement_content_achivement_dynamic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='teximonial_dynamic_content',
            name='texi_star',
            field=models.IntegerField(default=0),
        ),
    ]
