# Generated by Django 4.2.5 on 2025-01-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_teximonial_dynamic_content_texi_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='teximonial_dynamic_content',
            name='company_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='teximonial_dynamic_content',
            name='designation',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
