# Generated by Django 4.2.5 on 2025-01-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_remove_gallery_gallery_photo_gallery_bedroom_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falseceilng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falseceilling_photo', models.ImageField(default=0, upload_to='web_photos')),
            ],
        ),
    ]
