# Generated by Django 4.2.5 on 2025-01-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_falseceilng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Falseceilng',
        ),
    ]
