# Generated by Django 4.2.5 on 2025-01-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_delete_falseceilng'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Gallery_dynamic',
        ),
    ]
