# Generated by Django 4.2.5 on 2025-01-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_rename_gallery_gallery_dynamic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_heading', models.CharField(max_length=400)),
                ('sub_heading', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gallery_dynamic',
            new_name='Gallery_dynamic_content',
        ),
    ]
