# Generated by Django 4.2.5 on 2025-01-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_gallery_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='years_of_market',
            field=models.IntegerField(default=0),
        ),
    ]
