# Generated by Django 4.2.5 on 2025-01-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_profile_years_of_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instra_link',
            field=models.URLField(blank=True),
        ),
    ]
