# Generated by Django 4.2.5 on 2025-01-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_profile_facebook_link_profile_google_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soceity_work',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soceity_work',
            name='sub_work',
        ),
        migrations.AddField(
            model_name='soceity_work',
            name='company_name',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='soceity_work',
            name='company_photo',
            field=models.ImageField(default=0, upload_to='web_photos'),
        ),
        migrations.AddField(
            model_name='soceity_work',
            name='end_of_work_date',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='soceity_work',
            name='person_name',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='soceity_work',
            name='person_photo',
            field=models.ImageField(default=0, upload_to='web_photos'),
        ),
        migrations.AddField(
            model_name='soceity_work',
            name='person_post',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='soceity_work',
            name='work_description',
            field=models.CharField(default=0, max_length=800),
        ),
        migrations.AddField(
            model_name='soceity_work',
            name='work_designation',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AlterField(
            model_name='soceity_work',
            name='address',
            field=models.CharField(default=0, max_length=400),
        ),
    ]
