# Generated by Django 4.2.5 on 2025-01-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_remove_soceity_work_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teximonial_dynamic_content',
        ),
    ]
