# Generated by Django 4.2.5 on 2025-01-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_content',
        ),
        migrations.DeleteModel(
            name='Achivement_content',
        ),
        migrations.DeleteModel(
            name='Contact_content',
        ),
        migrations.DeleteModel(
            name='Gallery_content',
        ),
        migrations.DeleteModel(
            name='Landing_content',
        ),
        migrations.DeleteModel(
            name='Project_content',
        ),
        migrations.DeleteModel(
            name='Team_content',
        ),
        migrations.DeleteModel(
            name='Teximonial_content',
        ),
    ]
