# Generated by Django 4.2.5 on 2025-01-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_delete_about_content_delete_achivement_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monday_friday',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='saturday',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='sunday',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
