# Generated by Django 4.2.5 on 2025-01-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_delete_office_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Landing_dynamic_content',
        ),
    ]
