# Generated by Django 4.2.5 on 2025-01-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_delete_landing_dynamic_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_dynamic_content',
            new_name='About',
        ),
        migrations.RenameModel(
            old_name='Achivement_dynamic_content',
            new_name='Achivement',
        ),
        migrations.RenameModel(
            old_name='Gallery_dynamic_content',
            new_name='Gallery',
        ),
        migrations.RenameModel(
            old_name='Team_dynamic_content',
            new_name='Team',
        ),
    ]
