# Generated by Django 4.2.5 on 2025-01-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_rename_about_dynamic_content_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soceity_work',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
