# Generated by Django 4.2.5 on 2025-01-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_soceity_work_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='award',
            field=models.IntegerField(default=0),
        ),
    ]
