# Generated by Django 4.2.5 on 2025-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_profile_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_data',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
