# Generated by Django 4.2.5 on 2025-01-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_query_data_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_data',
            name='number',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
