# Generated by Django 4.2.5 on 2025-01-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_alter_query_data_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='google_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='instra_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
