# Generated by Django 4.2.5 on 2025-01-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_team_facebook_link_team_google_link_team_instra_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='facebook_link',
            new_name='designer_facebook_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='google_link',
            new_name='designer_google_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='instra_link',
            new_name='designer_instra_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='twitter_link',
            new_name='designer_twitter_link',
        ),
        migrations.AddField(
            model_name='team',
            name='engineer_facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='engineer_google_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='engineer_instra_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='engineer_twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='founder_facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='founder_google_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='founder_instra_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='founder_twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_google_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_instra_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
