# Generated by Django 4.2.5 on 2025-01-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_rename_facebook_link_team_designer_facebook_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='lighting_photo',
            new_name='floor_photo',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='tiles_photo',
            new_name='washroom_photo',
        ),
    ]
