# Generated by Django 5.1.5 on 2025-01-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_rename_lighting_photo_gallery_floor_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=400)),
                ('brand', models.CharField(max_length=400)),
                ('item_description', models.CharField(max_length=400)),
                ('remarks', models.CharField(max_length=400)),
            ],
        ),
    ]
