# Generated by Django 5.1.5 on 2025-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
