# Generated by Django 4.0.6 on 2025-02-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_query_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_data',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
