# Generated by Django 4.0.6 on 2025-02-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_alter_query_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(blank=True, upload_to='web_photos'),
        ),
    ]
