# Generated by Django 4.0.6 on 2025-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_alter_employee_work_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='award',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(default=9830229942),
        ),
    ]
