# Generated by Django 4.0.6 on 2025-02-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0078_alter_profile_award_alter_profile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
