# Generated by Django 4.0.6 on 2025-02-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_alter_service_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cat',
            field=models.CharField(blank=True, choices=[('wallpaer', 'wallpaer')], max_length=400),
        ),
    ]
