# Generated by Django 4.0.6 on 2025-02-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_service_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cat',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('Wallpaper', 'Wallpaper'), ('Door', 'Door'), ('Roof_Water_Profing', 'Roof_Water_Profing'), ('Paint', 'Paint'), ('Marble', 'Marble'), ('Siding_Window', 'Siding_Window'), ('Ceiling_Light', 'Ceiling_Light'), ('Falseceiling', 'Falseceiling'), ('Bathroom', 'Bathroom'), ('Basin', 'Basin'), ('Kitchen_Counter', 'Kitchen_Counter'), ('Tiles', 'Tiles')], max_length=400),
        ),
    ]
