# Generated by Django 4.0.6 on 2025-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_remove_service_cat_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.CharField(blank=True, choices=[('Pc', 'Pc'), ('Pcs', 'Pcs'), ('Kg', 'Kg'), ('Mtr', 'Mtr'), ('Sqft', 'Sqft'), ('Sqmtr', 'Sqmtr'), ('Roll', 'Roll'), ('Cft', 'Cft')], max_length=400),
        ),
    ]
