# Generated by Django 4.0.6 on 2025-02-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0082_service_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': '9. About'},
        ),
        migrations.AlterModelOptions(
            name='achivement',
            options={'verbose_name_plural': '8. Achivement'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': '2. Employee'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': '5. Gallery'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '1. Profile'},
        ),
        migrations.AlterModelOptions(
            name='query_data',
            options={'verbose_name_plural': '3. Query'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': '4. Section'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': '7. Service'},
        ),
        migrations.AlterModelOptions(
            name='soceity_work',
            options={'verbose_name_plural': '10. Soceity'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': '6. Team'},
        ),
        migrations.AlterModelOptions(
            name='term_policy',
            options={'verbose_name_plural': '11. Policy'},
        ),
    ]
