# Generated by Django 4.0.6 on 2025-02-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0083_alter_about_options_alter_achivement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.CharField(max_length=400),
        ),
    ]
