# Generated by Django 4.0.6 on 2025-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0086_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('Basin', 'Basin'), ('Bathroom', 'Bathroom'), ('Ceiling_Light', 'Ceiling Light'), ('Door', 'Door'), ('Falseceiling', 'False Ceiling'), ('Kitchen_Counter', 'Kitchen Counter'), ('Marble', 'Marble'), ('Paint', 'Paint'), ('Roof_Water_Profing', 'Roof Water Profing'), ('Siding_Window', 'Siding Window'), ('Tiles', 'Tiles'), ('Wallpaper', 'Wallpaper')], max_length=400),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(blank=True, choices=[('Cft', 'Cft'), ('Kg', 'Kg'), ('Mtr', 'Mtr'), ('Pc', 'Pc'), ('Pcs', 'Pcs'), ('Roll', 'Roll'), ('Sqft', 'Sqft'), ('Sqmtr', 'Sqmtr')], max_length=400),
        ),
    ]
