# Generated by Django 4.0.6 on 2025-02-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0087_alter_service_category_alter_service_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_caterory',
        ),
    ]
