# Generated by Django 4.0.6 on 2025-02-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0088_delete_service_caterory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soceity_work',
            options={'verbose_name_plural': '10. Soceity_work'},
        ),
        migrations.AlterModelOptions(
            name='term_policy',
            options={'verbose_name_plural': '11. Term_policy'},
        ),
    ]
