# Generated by Django 4.0.6 on 2025-02-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0089_alter_soceity_work_options_alter_term_policy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soceity_work',
            options={'verbose_name_plural': '10. Soceity'},
        ),
        migrations.AlterModelOptions(
            name='term_policy',
            options={'verbose_name_plural': '11. Policy'},
        ),
    ]
