# Generated by Django 4.0.6 on 2025-02-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_alter_soceity_work_options_alter_term_policy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(blank=True, choices=[('Cft', 'Cft'), ('Kg', 'Kg'), ('Mtr', 'Mtr'), ('Ltr', 'Ltr'), ('Pc', 'Pc'), ('Pcs', 'Pcs'), ('Roll', 'Roll'), ('Sqft', 'Sqft'), ('Sqmtr', 'Sqmtr')], max_length=400),
        ),
    ]
