# Generated by Django 4.0.6 on 2025-02-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0092_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('Basin', 'Basin'), ('Bathroom', 'Bathroom'), ('Ceiling-Light', 'Ceiling Light'), ('Door', 'Door'), ('Falseceiling', 'False Ceiling'), ('Kitchen-Counter', 'Kitchen Counter'), ('Marble', 'Marble'), ('Paint', 'Paint'), ('Roof-Water-Profing', 'Roof Water Profing'), ('Siding-Window', 'Siding Window'), ('Tiles', 'Tiles'), ('Wallpaper', 'Wallpaper')], max_length=400),
        ),
    ]
