# Generated by Django 4.0.6 on 2025-02-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0094_alter_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='achivement',
            options={'verbose_name_plural': 'Achivement'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='query_data',
            options={'verbose_name_plural': 'Query'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'Section'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='soceity_work',
            options={'verbose_name_plural': 'Soceity'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Team'},
        ),
        migrations.AlterModelOptions(
            name='term_policy',
            options={'verbose_name_plural': 'Policy'},
        ),
    ]
