# Generated by Django 4.0.6 on 2025-02-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0096_alter_gallery_bedroom_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='drawingroom_photo',
            new_name='paint_photo',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='floor_photo',
            new_name='plywood_photo',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='livingroom_photo',
            new_name='tiles_photo',
        ),
    ]
